baseURL = "https://nul.srht.site/"
title = "Nul's Litterbox"
languageCode = "en-us"
theme = "hello-friend-ng"
author = "Underscore Nul"
copyright = "(c) 2023 Underscore Nul"
enableGitInfo = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
homeSubtitle = "Projects and Rants from Underscore Nul"
description = "Clouded Leopard fur, rust dev, chronically online shitposter."

[taxonomies]
category = "categories"
tag = "tags"
project = "projects"

[[params.social]]
name = "mastodon"
url = "https://bark.lgbt/@nul"

[[params.social]]
name = "matrix"
url = "https://matrix.to/#/@nul:bark.lgbt"

[[params.social]]
name = "email"
url = "mailto:underscore.nul@proton.me"

[[params.social]]
name = "git"
url = "https://git.sr.ht/~nul"

[languages]
[languages.en]
title = "Nul's Litterbox"
[languages.en.params.logo]
logoText = "Nul's Litterbox"
logoHomeLink = "/"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
